### ISSUE TITLE
GLTF Rotate Model

### ISSUE THREAD

**Issue by Lozzad** [edsilv/aframe-workshop#1]
The tutorial asks us to rotate the model about the Y axis, which is already happening. Maybe starting with the model rotating around a different axis so that by following the tutorial it is 'fixed' would work?

**Comment by Lozzad** [comment]
Similar issue with debugUIenabled and vr-mode-ui being false already, not a massive issue just maybe having them on and cluttering the screen at first, then being turned off during the tutorial would help user satisfaction.

**Comment by edsilv** [comment]
Yep, right now it's in a very early state where I've simply got things working in some demo files and documented what I'm doing in the readme. It definitely needs more structure.

**Comment by edsilv** [comment]
I haven't decided yet whether I want the workshops to be a show and tell with follow-along coding, or more of a "figure it out yourself" kind of thing with complete reference files if you get stuck.

**Comment by Lozzad** [comment]
Personally I like the idea of the page being broken/cluttered and then the tutorial being about fixing it. Maybe a combination of that and reference files would work? I guess it depends on whether it is intended to be a tutorial about setting up the whole page/adding a-objects, or just for modifying them and leaving learners to work it out for themselves from the code.

**Comment by edsilv** [comment]
Hmm, not sure it's about "fixing" things as much as creating them...

Thinking that there may be people who just want to watch a talk and clone the code for their own reference later.

Others may want to code along - so I could create a new project and build each page from scratch using sections of the references while explaining what each bit does...

**Comment by edsilv** [comment]
The readme then acts as a high-level overview of what's happening in each file as opposed to an exhaustive explanation (I'll supply that on the day).

**Comment by Lozzad** [comment]
Yeah I guess I was thinking about coming to it as a novice rather than as a quick reference type of thing. High level overview is definitely the way to go. Any parts you'd like feedback on specifically? Because so far it's been really helpful for familiarising us with A-Frame and we don't really have much to criticise.

**Comment by edsilv** [comment]
Ok, cool - glad it's proving useful! I guess I'll just refine the high-level overview then. Maybe add something about controlling animations in 3D models.
